backend:
  name: github
  repo: koconno8/mercury-website  # Your GitHub repo
  branch: main
  base_url: https://auth.decapcms.org
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "home.md"
        label: "Home Content"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Intro Paragraph", name: "intro", widget: "text" }
