backend:
  name: github
  repo: koconno8/mercury-website
  branch: main
  auth_type: pkce

site_url: https://koconno8.github.io/mercury-website

media_folder: "images"
public_folder: "/images"

collections:
  - name: home
    label: Homepage
    files:
      - file: home.md
        label: Home Page Content
        name: home
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - { label: Intro, name: intro, widget: text }