backend:
  name: git-gateway
  branch: main
  name: github
  repo: koconno8/mercury-website
  branch: main


media_folder: "images"
public_folder: "/images"

collections:
  - name: home
    label: "Homepage"
    files:
      - file: "home.md"
        label: "Home Content"
        name: "home"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Tagline"
            name: "tagline"
            widget: "string"
          - label: "Intro Paragraph"
            name: "intro"
            widget: "text"
